import os
FLASK_API_KEY = os.getenv("FLASK_API_KEY")
FLASK_SERVER_IP = os.getenv("FLASK_SERVER_IP")
FLASK_ADMIN_EMAIL = os.getenv("FLASK_ADMIN_EMAIL")
FLASK_BACKUP = os.getenv("FLASK_BACKUP")
FLASK_CONFIG_PATH = os.getenv("FLASK_CONFIG_PATH")
